import {type Workspace,readiness,categories} from './model';
export function demoAction(input:Workspace,action:string,b:any){const w=structuredClone(input),by='Sample: you',id=()=>crypto.randomUUID(),now=new Date().toISOString();let a=w.assets.find(a=>a.id===b.assetId),q=w.questions.find(q=>q.id===b.questionId);if(q)a=w.assets.find(a=>a.id===q.assetId);const reopen=(ids:string[])=>{w.assets.filter(a=>ids.includes(a.id)&&a.status!=='excluded').forEach(a=>{a.status=a.content?'stale':'missing';a.reviewer=undefined;a.ownerApproval=undefined});w.tests.filter(t=>t.assetIds.some(x=>ids.includes(x))).forEach(t=>t.approved=false);w.runs.forEach(r=>r.stale=true)};let message='Sample change applied.';let changed:string[]=[];
 switch(action){
 case 'approve_question':if(!q||q.status!=='suggested')throw Error('Select a draft question.');q.text=b.text||q.text;q.assignedTo=b.assignedTo||q.assignedTo;q.status='approved';q.reviewer=by;message='Sample question approved and delivered to the inbox.';break;
 case 'answer':if(!q||!a||!['approved','deferred'].includes(q.status))throw Error('The question needs expert approval first.');if(!b.answer)throw Error('Add an answer.');reopen([a.id]);q.answer=b.answer;q.status='answered';a.content=b.answer;a.status='review';a.version++;a.kind='Proposed interpretation';{const sourceId=id();w.sources.unshift({id:sourceId,key:'',name:'Sample answer — '+a.title+'.txt',mime:'text/plain',size:b.answer.length,hash:sourceId,version:1,uploadedBy:by,at:now,access:'project',category:'Marketing / Campaign audience selection / US',assetIds:[a.id],text:b.answer,extraction:'Contributor statement; expert review required',consent:false,sample:true});a.evidence.push({sourceId,location:'Full answer',quote:b.answer})}changed=[a.id];message='Sample answer captured; expert review is pending.';break;
 case 'question':if(!a||!b.text)throw Error('Select a requirement and write a question.');w.questions.unshift({id:id(),assetId:a.id,text:b.text,why:b.why||'Close the outstanding gap.',effort:'3 minutes',assignedTo:b.assignedTo||a.owner,status:'suggested',answer:'',createdBy:by});message='Sample follow-up drafted for question review.';break;
 case 'defer':if(!q)throw Error('Question not found.');q.status='deferred';q.assignedTo=b.assignedTo||q.assignedTo;message='Question deferred; the gap remains open.';break;
 case 'verify':if(!a||!a.content||!a.evidence.length||!a.owner||!a.acceptance)throw Error('Explanation, evidence, owner, and acceptance criteria are required.');if(!b.evidenceChecked)throw Error('Confirm your evidence review.');if(a.conflict&&!b.resolution)throw Error('Record how the conflict was resolved.');a.conflict='';a.reviewer=by;a.reviewedAt=now;a.reviewedVersion=a.version;a.status=a.critical?'owner_review':'verified';a.kind=a.critical?'Proposed interpretation':'Approved rule';if(!a.critical)w.questions.filter(q=>q.assetId===a!.id).forEach(q=>q.status='resolved');changed=[a.id];message=a.critical?'Expert verified. Business-owner sign-off remains open.':'One sample requirement verified.';break;
 case 'owner_signoff':if(!a||a.status!=='owner_review')throw Error('Complete expert review first.');a.ownerApproval=by;a.status='verified';a.kind='Approved rule';w.questions.filter(q=>q.assetId===a!.id).forEach(q=>q.status='resolved');changed=[a.id];message='Sample critical rule approved; the blocker is closed.';break;
 case 'edit_asset':if(!a||!b.content)throw Error('Add an interpretation.');reopen([a.id]);a.content=b.content;a.owner=b.owner||a.owner;a.acceptance=b.acceptance||a.acceptance;a.status='review';a.version++;if(b.sourceId){if(!b.quote||!b.location)throw Error('Add an evidence passage and location.');a.evidence.push({sourceId:b.sourceId,quote:b.quote,location:b.location})}message='Sample draft updated; approval reopened.';break;
 case 'classify':{const s=w.sources.find(s=>s.id===b.sourceId);if(!s)throw Error('Source not found.');s.category=b.category;s.assetIds=b.assetIds||s.assetIds;message='Sample evidence organized.';break;}
 case 'save_note':{if(!b.content)throw Error('Add a contribution.');const sourceId=id();w.sources.unshift({id:sourceId,key:'',name:b.name||'Sample note.txt',mime:'text/plain',size:b.content.length,hash:sourceId,version:1,uploadedBy:by,at:now,access:b.access||'project',category:b.category||'Needs classification',assetIds:b.assetIds||[],text:b.content,extraction:'Sample contribution; not stored on the server',consent:false,sample:true,link:b.link});message='Sample note added for this preview session only.';break;}
 case 'blueprint':if(b.scope!==w.scope){w.scope=b.scope;w.blueprintVersion++;reopen(w.assets.map(a=>a.id))}w.client=b.client||w.client;message='Sample scope version updated; requirements need revalidation.';break;
 case 'add_requirement':w.assets.push({id:id(),title:b.title,category:b.category||categories[0],critical:!!b.critical,owner:b.owner||by,status:'missing',content:'',acceptance:b.acceptance||'Evidence and expert review',evidence:[],version:1,conflict:'',kind:'Proposed interpretation',fields:['Explanation','Evidence','Owner','Acceptance criteria']});w.blueprintVersion++;message='Sample requirement added.';break;
 case 'exclude':if(!a||!b.reason)throw Error('Record an exclusion reason.');reopen([a.id]);a.status='excluded';a.exclusion=b.reason;w.blueprintVersion++;message='Sample exclusion recorded.';break;
 case 'reopen':if(a)reopen([a.id]);message='Sample requirement and its tests reopened.';break;
 case 'expert':w.experts.push({name:b.name,role:b.role,coverage:b.coverage,proof:b.proof});message='Sample expert added.';break;
 case 'reject':if(!a||!b.reason)throw Error('Provide a clarification request.');reopen([a.id]);a.status='draft';w.questions.unshift({id:id(),assetId:a.id,text:b.reason,why:'Expert requested clarification.',effort:'3 minutes',assignedTo:a.owner,status:'suggested',answer:'',createdBy:by});message='Sample follow-up returned to question review.';break;
 case 'settings':w.settings={...w.settings,...Object.fromEntries(Object.entries(b).filter(([k])=>k in w.settings))};message='Sample reminder preferences updated.';break;
 case 'approve_test':{const t=w.tests.find(t=>t.id===b.testId);if(!t)throw Error('Case not found.');t.input=b.input||t.input;t.expected=b.expected||t.expected;t.approved=true;t.version=(t.version||1)+1;w.runs.forEach(r=>r.stale=true);message='Sample acceptance case approved.';break;}
 case 'add_test':w.tests.push({id:id(),name:b.name,input:b.input,expected:b.expected,split:b.split,approved:false,assetIds:[b.assetId]});message='Sample test drafted.';break;
 case 'grade':{const run=w.runs.find(r=>r.id===b.runId),result=run?.results.find(r=>r.caseId===b.caseId);if(!result||run?.stale)throw Error('This comparison is stale or missing.');result.beforePass=!!b.beforePass;result.afterPass=!!b.afterPass;result.gradedBy=by;message='Illustrative outputs graded in sample mode.';break;}
 case 'test_failure':{const t=w.tests.find(t=>t.id===b.testId);if(t&&b.kind==='context')reopen(t.assetIds);message=b.kind==='context'?'Sample context gap reopened.':'Sample engineering issue recorded.';break;}
 case 'release':if(!readiness(w).ready)throw Error('Verify every applicable requirement first.');{const version=w.releases.length+1;w.releases.unshift({id:id(),version,at:now,by,package:{sample:true,format:'discovery-context/1',version,scope:w.scope,blueprintVersion:w.blueprintVersion,assets:structuredClone(w.assets.filter(a=>a.status==='verified')),sources:structuredClone(w.sources),tests:structuredClone(w.tests),evaluations:structuredClone(w.runs)}});message=`Sample context v${version} released.`;}break;
 case 'refresh':{const s=w.sources.find(s=>s.id===b.sourceId);if(s)reopen(s.assetIds);message='Sample source change reopened dependent knowledge and tests.';break;}
 case 'extract':{if(!b.consent)throw Error('Confirm sample processing.');const s=w.sources.find(s=>s.id===b.sourceId);if(!s)throw Error('Select a sample source.');const target=w.assets.find(a=>a.id===(s.assetIds[0]||'a3'))!;reopen([target.id]);target.status='review';target.content=s.text.slice(0,1500);target.version++;target.evidence.push({sourceId:s.id,location:'Illustrative source excerpt',quote:s.text.slice(0,1000)});s.extraction='Illustrative extraction shown; no model was called.';s.consent=true;changed=[target.id];message='Sample extraction produced a draft for review. No live AI call.';break;}
 case 'suggest':{const target=w.assets.find(a=>a.critical&&a.status!=='verified')||w.assets[0];w.questions.unshift({id:id(),assetId:target.id,text:`Which approved evidence resolves ${target.title.toLowerCase()}?`,why:'Illustrative gap-driven question; expert approval required.',effort:'3 minutes',assignedTo:target.owner,status:'suggested',answer:'',createdBy:'Sample suggestion'});message='Illustrative question drafted; no AI call.';break;}
 case 'evaluate':{const cases=w.tests.filter(t=>t.approved);if(!cases.length)throw Error('Approve at least one test case first.');w.runs.unshift({id:id(),at:now,model:'Illustrative sample — no model run',baseline:'Sample without approved context',updated:'Sample current context',stale:false,results:cases.map(t=>({caseId:t.id,test:structuredClone(t),before:'I need the approved operating rule before deciding.',after:w.assets.filter(a=>t.assetIds.includes(a.id)).every(a=>a.status==='verified')?t.expected:'This requirement is not yet verified. Request expert review.',beforePass:null,afterPass:null}))});message='Illustrative comparison created. This is not measured agent performance.';break;}
 default:throw Error('This action requires a signed-in pilot workspace.');
 }
 w.events.unshift({id:id(),at:now,by,action,detail:message});w.receipts.unshift({id:id(),at:now,by,message,assetIds:changed});return {w,message};
}
