export type Role='admin'|'expert'|'owner'|'contributor'|'viewer';
export type Evidence={sourceId:string;location:string;quote:string};
export type Asset={id:string;title:string;category:string;critical:boolean;owner:string;status:'missing'|'draft'|'review'|'owner_review'|'verified'|'stale'|'excluded';content:string;acceptance:string;evidence:Evidence[];version:number;conflict:string;reviewer?:string;reviewerId?:string;reviewedVersion?:number;ownerId?:string;ownerApproval?:string;reviewedAt?:string;kind:'Observed practice'|'Proposed interpretation'|'Approved rule';fields:string[];exclusion?:string};
export type Question={id:string;assetId:string;text:string;why:string;effort:string;assignedTo:string;status:'suggested'|'approved'|'answered'|'resolved'|'deferred';answer:string;createdBy:string;reviewer?:string;parentId?:string;access?:'project'|'reviewers'};
export type Source={id:string;name:string;mime:string;size:number;hash:string;version:number;previousId?:string;key:string;uploadedBy:string;at:string;access:'project'|'reviewers';category:string;assetIds:string[];text:string;extraction:string;consent:boolean;sample:boolean;link?:string};
export type Receipt={id:string;at:string;by:string;message:string;assetIds:string[];sourceIds?:string[]};
export type TestCase={id:string;name:string;input:string;expected:string;split:'fixed'|'held-out'|'regression';approved:boolean;assetIds:string[];version?:number};
export type TestRun={id:string;at:string;model:string;baseline:string;updated:string;results:{caseId:string;test?:TestCase;before:string;after:string;beforePass:boolean|null;afterPass:boolean|null;gradedBy?:string}[];stale:boolean};
export type Release={id:string;version:number;at:string;by:string;package:any};
export type Workspace={name:string;client:string;scope:string;blueprintVersion:number;sample:boolean;assets:Asset[];questions:Question[];sources:Source[];receipts:Receipt[];tests:TestCase[];runs:TestRun[];releases:Release[];events:{id:string;at:string;by:string;action:string;detail:string}[];settings:{quietStart:string;quietEnd:string;frequency:string;paused:boolean;recognition:boolean};experts:{name:string;role:string;coverage:string;proof:string}[]};
export const categories=['Process maps','Rules & guardrails','Skills','Ontology & context','Data & tools','Outputs & evaluations'];
export function readiness(w:Workspace){const applicable=w.assets.filter(a=>a.status!=='excluded');return {total:applicable.length,captured:applicable.filter(a=>a.content.trim()&&a.evidence.length).length,verified:applicable.filter(a=>a.status==='verified').length,blockers:applicable.filter(a=>a.critical&&a.status!=='verified'),review:applicable.filter(a=>['review','owner_review','stale'].includes(a.status)),fields:applicable.reduce((n,a)=>n+(a.content?1:0)+(a.evidence.length?1:0)+(a.owner?1:0)+(a.acceptance?1:0),0),fieldTotal:applicable.length*4,ready:applicable.length>0&&applicable.every(a=>a.status==='verified')};}
export function seedWorkspace(sample=true):Workspace{
 const labels=['Audience selection workflow','Approval and activation handoff','Recent-contact suppression','Overrides and escalation','Assemble an eligible audience','Prepare an approval packet','Customer and consent definitions','Eligible audience measures','Consent freshness control','Platform tools and permissions','Audience delivery standard','Acceptance test pack'];
 const contents=['Campaign brief → consent check → suppressions → audience QA → owner approval → activation.','Campaign manager prepares the audience. Marketing owner approves activation. Data owner resolves data issues.','Exclude customers contacted in the previous 30 days. A practitioner demonstration uses 14 days.','Any exception needs written marketing-owner approval, named scope, and an expiry date.','Check consent and recency, apply suppressions, calculate audience counts, and produce the approval packet.','Include audience size, exclusions, data timestamps, evidence and the owner decision.','A customer is a unique CRM customer ID. Active consent must cover the selected channel.','Eligible audience equals consented customers minus policy exclusions and duplicate customer IDs.','','Read consent and contact-history data. Audience activation requires a separate authorized approval action.','Deliver customer IDs, channel eligibility, suppression reasons, source timestamps and an approval record.',''];
 const source:Source={id:'s-playbook',name:'Campaign operating playbook.txt',mime:'text/plain',size:0,hash:'sample-playbook',version:1,key:'',uploadedBy:'Sample: Ava Chen',at:new Date().toISOString(),access:'project',category:'Marketing / Campaign audience selection / US',assetIds:labels.map((_,i)=>`a${i+1}`),text:contents.filter(Boolean).map((t,i)=>`Section ${i+1}: ${t}`).join('\n\n'),extraction:'Sample evidence',consent:false,sample:true};
 const status=(i:number):Asset['status']=>[8,11].includes(i)?'missing':[2,3,9].includes(i)?'review':'verified';
 const assets:Asset[]=labels.map((title,i)=>({id:`a${i+1}`,title,category:categories[Math.floor(i/2)],critical:[2,3,8].includes(i),owner:['Sample: Ava Chen','Sample: Liam Brooks','Sample: Elena Ortiz'][i===8?2:i%2],status:sample?status(i):'missing',content:sample?contents[i]:'',acceptance:'A scoped explanation, supporting evidence, accountable owner, and expert approval.',evidence:sample&&contents[i]?[{sourceId:'s-playbook',location:`Playbook: ${title}`,quote:contents[i]}]:[],version:1,conflict:sample&&i===2?'The playbook requires 30 days; the practitioner demonstration shows 14 days.':'',kind:sample&&status(i)==='verified'?'Approved rule':'Proposed interpretation',fields:['Explanation','Evidence','Owner','Acceptance criteria'],...(sample&&status(i)==='verified'?{reviewer:'Sample: Maya Patel',ownerApproval:'Sample: Liam Brooks',reviewedAt:new Date().toISOString()}: {})}));
 return {name:'Campaign audience selection',client:sample?'Northstar Retail':'My organization',scope:'United States · Email and paid media; EU and SMS excluded',blueprintVersion:1,sample,assets,questions:[{id:'q1',assetId:'a3',text:'Is the 14-day setting an approved exception to the 30-day suppression rule? Provide approval, scope, and expiry.',why:'Resolves a critical policy conflict before audience activation.',effort:'3 minutes',assignedTo:'Campaign owner',status:'suggested',answer:'',createdBy:'Blueprint'},{id:'q2',assetId:'a9',text:'How fresh must consent data be, and what happens if it is older than that limit?',why:'Closes a missing data guardrail.',effort:'3 minutes',assignedTo:'Data owner',status:'suggested',answer:'',createdBy:'Blueprint'},{id:'q3',assetId:'a12',text:'Which examples and edge cases must the audience-selection agent pass before acceptance?',why:'Establishes expert-reviewed success criteria.',effort:'5 minutes',assignedTo:'Domain expert',status:'suggested',answer:'',createdBy:'Blueprint'}],sources:sample?[source,{...source,id:'s-demo',name:'Practitioner demonstration transcript.txt',hash:'sample-demo',assetIds:['a3'],text:'00:42 — I set the previous-contact exclusion to 14 days in the audience builder.\n01:04 — I do not know if the shorter interval has been formally approved.',extraction:'Observed practice; policy conflict',uploadedBy:'Sample: Ava Chen'}]:[],receipts:[],tests:[{id:'t1',name:'Recently contacted customer',input:'Customer has email consent and was contacted 20 days ago. Include them?',expected:'Exclude: the contact is within the 30-day suppression period.',split:'fixed',approved:false,assetIds:['a3']},{id:'t2',name:'Stale consent data',input:'Consent records are 30 hours old. May the campaign activate?',expected:'Block activation and ask the data owner for current consent evidence.',split:'held-out',approved:false,assetIds:['a9']},{id:'t3',name:'Missing override approval',input:'Campaign manager requests an exception without written owner approval. Proceed?',expected:'Do not apply the exception. Request written owner approval with scope and expiry.',split:'regression',approved:false,assetIds:['a4']}],runs:[],releases:[],events:[],settings:{quietStart:'18:00',quietEnd:'09:00',frequency:'Daily digest',paused:false,recognition:true},experts:sample?[{name:'Ava Chen',role:'Campaign practitioner',coverage:'US email and paid media',proof:'Sample workflow demonstration'},{name:'Maya Patel',role:'Domain expert',coverage:'Marketing operations',proof:'Sample review of suppression exceptions'},{name:'Liam Brooks',role:'Business owner',coverage:'Campaign approvals',proof:'Sample approval ownership'},{name:'Elena Ortiz',role:'Data owner',coverage:'Consent and contact history',proof:'Sample data freshness demonstration'}]:[]};
}
