import {env} from 'cloudflare:workers';
import {currentUser} from './auth';
import type {Workspace,Role} from './model';
export class AppError extends Error{constructor(message:string,public code=400){super(message)}}
export function db(){if(!env.DB)throw new AppError('Workspace storage is not available. Please retry after setup completes.',503);return env.DB;}
export function bucket(){if(!env.BUCKET)throw new AppError('File storage is not available yet.',503);return env.BUCKET;}
export async function identity(){const u=await currentUser();if(!u)throw new AppError('Sign in to continue.',401);return u;}
export function sameOrigin(req:Request){const o=req.headers.get('origin');if(o!==new URL(req.url).origin)throw new AppError('This request must come from the workspace.',403);}
export async function project(id:string,userId:string){const row=await db().prepare('SELECT p.*,m.role FROM projects p JOIN members m ON m.project_id=p.id WHERE p.id=? AND m.user_id=?').bind(id,userId).first<any>();if(!row)throw new AppError('Workspace not found or access not granted.',404);return {...row,state:JSON.parse(row.state) as Workspace,role:row.role as Role};}
export function permitted(role:Role,roles:Role[]){if(!roles.includes(role))throw new AppError('Your role cannot perform this action.',403)}
export function reviewRole(role:Role){return ['admin','expert','owner'].includes(role)}
export function sourceVisible(s:any,role:Role){return s.access==='project'||reviewRole(role)}
export function safeState(w:Workspace,role:Role){if(reviewRole(role))return w;const hidden=new Set(w.sources.filter(s=>!sourceVisible(s,role)).map(s=>s.id));const hiddenAssets=new Set(w.assets.filter(a=>a.evidence.some(e=>hidden.has(e.sourceId))).map(a=>a.id));return {...w,sources:w.sources.filter(s=>!hidden.has(s.id)),assets:w.assets.filter(a=>!hiddenAssets.has(a.id)),questions:w.questions.filter(q=>q.access!=='reviewers'&&!hiddenAssets.has(q.assetId)),receipts:w.receipts.filter(r=>!(r.sourceIds||[]).some(id=>hidden.has(id))&&!r.assetIds.some(id=>hiddenAssets.has(id))),tests:w.tests.filter(t=>!t.assetIds.some(id=>hiddenAssets.has(id))),runs:[],releases:[],events:[]};}
export function event(w:Workspace,by:string,action:string,detail:string){w.events.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),by,action,detail});w.events=w.events.slice(0,300);}
export function receipt(w:Workspace,by:string,message:string,assetIds:string[]=[],sourceIds:string[]=[]){w.receipts.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),by,message,assetIds,sourceIds});w.receipts=w.receipts.slice(0,100);}
export async function save(p:any,by:string,action:string,detail:string,effects?:(marker:string)=>D1PreparedStatement[]){event(p.state,by,action,detail);const marker=p.state.events[0].id;const statement=db().prepare('UPDATE projects SET state=?,name=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(p.state),p.state.name,p.id,p.revision);const results=await db().batch([statement,...(effects?effects(marker):[])]);if(!results[0].meta.changes)throw new AppError('Another person updated this workspace. Refresh and try again; your change was not saved.',409);return p.revision+1;}
export function fail(e:unknown){console.error(e instanceof Error?e.message:'Request failed');return Response.json({error:e instanceof AppError?e.message:'The request could not be completed. Your last saved work is safe.'},{status:e instanceof AppError?e.code:500})}
export const text=(x:unknown,max=20000)=>typeof x==='string'?x.trim().slice(0,max):'';
export async function hash(bytes:ArrayBuffer|Uint8Array|string){const b=typeof bytes==='string'?new TextEncoder().encode(bytes):bytes;return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b as BufferSource))).map(b=>b.toString(16).padStart(2,'0')).join('');}
export function invalidate(w:Workspace,ids:string[]){for(const a of w.assets.filter(a=>ids.includes(a.id))){if(a.status!=='missing'&&a.status!=='excluded')a.status='stale';a.reviewer=undefined;a.reviewerId=undefined;a.reviewedVersion=undefined;a.ownerId=undefined;a.ownerApproval=undefined;a.reviewedAt=undefined;}for(const t of w.tests.filter(t=>t.assetIds.some(id=>ids.includes(id))))t.approved=false;for(const r of w.runs)r.stale=true;}
export function aiConfig(){const cfg=env as any;return {ready:!!cfg.OPENAI_API_KEY,model:cfg.OPENAI_MODEL||'gpt-4.1'};}
