import {seedWorkspace,readiness,type Role} from '../../lib/model';
import {db,bucket,identity,project,permitted,safeState,sourceVisible,save,event,receipt,fail,AppError,sameOrigin,text,hash,invalidate,aiConfig,reviewRole} from '../../lib/server';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{
 const u=await identity(),url=new URL(req.url),id=url.searchParams.get('project');
 if(!id){const projects=await db().prepare('SELECT p.id,p.name,m.role FROM projects p JOIN members m ON m.project_id=p.id WHERE m.user_id=? ORDER BY p.created_at DESC').bind(u.userId).all();return Response.json({projects:projects.results,user:u,ai:aiConfig()});}
 const p=await project(id,u.userId);
 if(url.searchParams.has('source')){const s=p.state.sources.find((s:any)=>s.id===url.searchParams.get('source'));if(!s||!sourceVisible(s,p.role))throw new AppError('Source not found.',404);const obj=s.key?await bucket().get(s.key):null;if(s.key&&!obj)throw new AppError('Source bytes are unavailable.',404);return new Response(obj?obj.body:s.text,{headers:{'Content-Type':s.mime||'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(s.name)}`,'X-Content-Type-Options':'nosniff','Cache-Control':'private, no-store'}});}
 if(url.searchParams.has('release')){permitted(p.role,['admin','expert','owner']);const r=p.state.releases.find((r:any)=>r.id===url.searchParams.get('release'));if(!r)throw new AppError('Release not found.',404);return new Response(JSON.stringify(r.package,null,2),{headers:{'Content-Type':'application/json','Content-Disposition':`attachment; filename="discovery-context-v${r.version}.json"`,'Cache-Control':'private, no-store'}});}
 const members=await db().prepare('SELECT user_id AS userId,email,name,role FROM members WHERE project_id=?').bind(id).all();return Response.json({id,revision:p.revision,role:p.role,state:safeState(p.state,p.role),members:members.results,user:u,ai:aiConfig()},{headers:{'Cache-Control':'private, no-store'}});
 }catch(e){return fail(e)}}
export async function POST(req:Request){try{
 sameOrigin(req);const u=await identity();const isFile=req.headers.get('content-type')?.includes('multipart/form-data');const form=isFile?await req.formData():null;if(!form&&!req.headers.get('content-type')?.includes('application/json'))throw new AppError('Use a JSON or file request.',415);const b:any=form?Object.fromEntries(form.entries()):await req.json();if(!b||typeof b!=='object'||Array.isArray(b))throw new AppError('Invalid request.');const action=text(b.action,60);
 if(action==='create'){const id=crypto.randomUUID(),state=seedWorkspace(b.sample===true||b.sample==='true');state.client=text(b.client,120)||state.client;for(const a of state.assets)if(!state.sample)a.owner=u.displayName;event(state,u.displayName,'Workspace created',state.sample?'Synthetic campaign demonstration':'Empty campaign discovery workspace');await db().batch([db().prepare('INSERT INTO projects(id,owner,name,state,created_at) VALUES(?,?,?,?,?)').bind(id,u.userId,state.name,JSON.stringify(state),new Date().toISOString()),db().prepare('INSERT INTO members(project_id,user_id,email,name,role) VALUES(?,?,?,?,?)').bind(id,u.userId,u.email,u.displayName,'admin')]);return Response.json({id});}
 if(action==='accept_invite'){const token=text(b.token,200),h=await hash(token);const row=await db().prepare('SELECT * FROM invites WHERE hash=? AND expires>? AND used_by IS NULL').bind(h,new Date().toISOString()).first<any>();if(!row)throw new AppError('This invitation has expired or has already been used.');const results=await db().batch([db().prepare('INSERT OR IGNORE INTO members(project_id,user_id,email,name,role) SELECT project_id,?,?,?,role FROM invites WHERE hash=? AND used_by IS NULL AND expires>?').bind(u.userId,u.email,u.displayName,h,new Date().toISOString()),db().prepare('UPDATE invites SET used_by=? WHERE hash=? AND used_by IS NULL').bind(u.userId,h)]);if(!results[1].meta.changes)throw new AppError('Invitation already used.',409);return Response.json({id:row.project_id});}
 const p=await project(text(b.project,100),u.userId);permitted(p.role,['admin','expert','owner','contributor']);if(Number(b.revision)!==p.revision)throw new AppError('The workspace changed. Refresh before saving; your input has not been discarded.',409);const w=p.state,by=u.displayName;
 const getAsset=()=>{const a=w.assets.find((a:any)=>a.id===b.assetId);if(!a)throw new AppError('Requirement not found.');if(a.evidence.some((e:any)=>{const s=w.sources.find((s:any)=>s.id===e.sourceId);return s&&!sourceVisible(s,p.role)}))throw new AppError('This requirement needs reviewer access.',403);return a;};
 const getQuestion=()=>{const q=w.questions.find((q:any)=>q.id===b.questionId);if(!q)throw new AppError('Question not found.');if(q.access==='reviewers'&&!reviewRole(p.role))throw new AppError('Reviewer access required.',403);b.assetId=q.assetId;getAsset();return q;};
 let message='Saved.',extra:any={};let effects:((marker:string)=>D1PreparedStatement[])|undefined;
 switch(action){
 case 'upload':{const file=form?.get('file');if(!(file instanceof File)||!file.size)throw new AppError('Choose a file to upload.');if(file.size>12*1024*1024)throw new AppError('This pilot accepts files up to 12 MB.');const ext=file.name.split('.').pop()?.toLowerCase();if(!['pdf','doc','docx','ppt','pptx','xls','xlsx','csv','tsv','txt','md','json','png','jpg','jpeg','webp','mp3','wav','m4a','webm','mp4'].includes(ext||''))throw new AppError('This file type is not supported.');const bytes=await file.arrayBuffer(),digest=await hash(bytes);const dup=w.sources.find((s:any)=>s.hash===digest);if(dup){if(!sourceVisible(dup,p.role))throw new AppError('This source already exists with restricted access. Ask an expert to link it.');receipt(w,by,`Duplicate linked to ${dup.name}; no new coverage or points.`,dup.assetIds,[dup.id]);message='Duplicate recognized; existing evidence preserved.';break;}
 const previous=w.sources.find((s:any)=>s.id===b.previousId);if(b.previousId&&!previous)throw new AppError('Previous source not found.');if(previous&&!sourceVisible(previous,p.role))throw new AppError('Reviewer access required.',403);const id=crypto.randomUUID(),key=`${p.id}/${id}`;const rawIds=String(b.assetIds||'').split(',').filter(Boolean);const assetIds=rawIds.filter((id:string)=>w.assets.some((a:any)=>a.id===id));const content=['txt','md','csv','tsv','json'].includes(ext||'')?new TextDecoder().decode(bytes).slice(0,80000):'';await bucket().put(key,bytes,{httpMetadata:{contentType:file.type||'application/octet-stream'}});w.sources.unshift({id,name:file.name.slice(0,200),mime:file.type||'application/octet-stream',size:file.size,hash:digest,version:previous?previous.version+1:1,previousId:previous?.id,key,uploadedBy:by,at:new Date().toISOString(),access:previous?.access==='reviewers'?'reviewers':b.access==='reviewers'?'reviewers':'project',category:text(b.category,200)||'Needs classification',assetIds,text:content,extraction:'Awaiting processing consent',consent:false,sample:false});if(previous)invalidate(w,[...new Set([...previous.assetIds,...w.assets.filter((a:any)=>a.evidence.some((e:any)=>e.sourceId===previous.id)).map((a:any)=>a.id)])]);receipt(w,by,`${file.name} stored with its original bytes. ${assetIds.length} requirements linked; expert verification remains open.`,assetIds,[id]);message=previous?'New source version saved. Dependent knowledge reopened.':'File stored. Review classification before AI extraction.';extra.sourceId=id;break;}
 case 'save_note':{const content=text(b.content,80000);if(!content)throw new AppError('Add a contribution first.');const id=crypto.randomUUID(),key=`${p.id}/${id}`;await bucket().put(key,content,{httpMetadata:{contentType:'text/plain'}});const assetIds=Array.isArray(b.assetIds)?b.assetIds.filter((id:any)=>w.assets.some((a:any)=>a.id===id)):[];let link=text(b.link,1000);if(link&&!/^https?:\/\//i.test(link))throw new AppError('Use an http or https reference link.');w.sources.unshift({id,key,name:text(b.name,200)||'Expert contribution.txt',mime:'text/plain',size:new TextEncoder().encode(content).length,hash:await hash(content),version:1,uploadedBy:by,at:new Date().toISOString(),access:b.access==='reviewers'?'reviewers':'project',category:text(b.category,200)||'Needs classification',assetIds,text:content,extraction:'Awaiting processing consent',consent:false,sample:false,link});receipt(w,by,'Contribution preserved as source evidence. No requirement has been approved automatically.',assetIds,[id]);extra.sourceId=id;message='Contribution saved.';break;}
 case 'classify':{const s=w.sources.find((s:any)=>s.id===b.sourceId);if(!s||!sourceVisible(s,p.role))throw new AppError('Source not found.');s.category=text(b.category,200)||'Needs classification';s.assetIds=(Array.isArray(b.assetIds)?b.assetIds:[]).filter((id:any)=>w.assets.some((a:any)=>a.id===id));message='Source classification updated.';break;}
 case 'question':{permitted(p.role,['admin','expert','owner']);getAsset();const value=text(b.text,3000);if(!value)throw new AppError('Write a question.');w.questions.unshift({id:crypto.randomUUID(),assetId:b.assetId,text:value,why:text(b.why,500)||'Close the outstanding requirement.',effort:'3 minutes',assignedTo:text(b.assignedTo,200)||'Process owner',status:'suggested',answer:'',createdBy:by,parentId:text(b.parentId,100)||undefined});message='Question drafted for expert approval.';break;}
 case 'approve_question':{permitted(p.role,['admin','expert']);const q=getQuestion();if(q.status!=='suggested')throw new AppError('Only a draft question can be approved.');q.text=text(b.text,3000)||q.text;q.assignedTo=text(b.assignedTo,200)||q.assignedTo;q.status='approved';q.reviewer=by;message='Question approved and delivered to the in-app inbox.';break;}
 case 'answer':{const q=getQuestion();if(!['approved','deferred'].includes(q.status))throw new AppError('This question is not awaiting an answer.');const answer=text(b.answer,15000);if(!answer)throw new AppError('Write your answer.');q.answer=answer;q.status='answered';const a=getAsset();invalidate(w,[a.id]);a.content=answer;a.status='review';a.kind='Proposed interpretation';a.version++;a.reviewer=undefined;a.ownerApproval=undefined;const id=crypto.randomUUID(),key=`${p.id}/${id}`;await bucket().put(key,answer,{httpMetadata:{contentType:'text/plain'}});w.sources.unshift({id,key,name:`Answer — ${a.title}.txt`,mime:'text/plain',size:answer.length,hash:await hash(answer),version:1,uploadedBy:by,at:new Date().toISOString(),access:a.evidence.some((e:any)=>w.sources.find((s:any)=>s.id===e.sourceId)?.access==='reviewers')?'reviewers':'project',category:`${w.client} / ${w.name} / ${a.category}`,assetIds:[a.id],text:answer,extraction:'Contributor statement; needs verification',consent:false,sample:false});a.evidence.push({sourceId:id,location:'Full answer',quote:answer.slice(0,1500)});receipt(w,by,`Answer captured for ${a.title}. Awaiting expert review; verification has not increased.`,[a.id]);message='Answer saved and routed to expert review.';break;}
 case 'defer':{const q=getQuestion();if(['resolved','suggested'].includes(q.status))throw new AppError('This question cannot be deferred.');q.status='deferred';q.assignedTo=text(b.assignedTo,200)||q.assignedTo;message='Question deferred or referred; the gap remains open.';break;}
 case 'edit_asset':{permitted(p.role,['admin','expert','owner']);const a=getAsset();invalidate(w,[a.id]);const content=text(b.content,20000);if(!content)throw new AppError('Add a proposed interpretation.');a.content=content;a.owner=text(b.owner,200)||a.owner;a.acceptance=text(b.acceptance,4000)||a.acceptance;a.status='review';a.kind='Proposed interpretation';a.version++;a.reviewer=undefined;a.ownerApproval=undefined;if(b.sourceId){const s=w.sources.find((s:any)=>s.id===b.sourceId);if(!s||!sourceVisible(s,p.role))throw new AppError('Evidence not found.');const quote=text(b.quote,4000),location=text(b.location,400);if(!quote||!location)throw new AppError('Add an evidence passage and location.');a.evidence.push({sourceId:s.id,location,quote});if(!s.assetIds.includes(a.id))s.assetIds.push(a.id);}message='Interpretation revised; expert approval reopened.';break;}
 case 'verify':{permitted(p.role,['admin','expert']);const a=getAsset();if(!['review','draft','stale'].includes(a.status))throw new AppError('This requirement is not awaiting expert review.');if(!a.content||!a.owner||!a.acceptance||!a.evidence.length)throw new AppError('Explanation, evidence, owner, and acceptance criteria are required.');if(b.evidenceChecked!==true)throw new AppError('Confirm that you checked the original evidence.');if(a.conflict&&!text(b.resolution,2000))throw new AppError('Record how the conflict was resolved.');if(a.conflict){event(w,by,'Conflict resolved',text(b.resolution,2000));a.conflict='';}a.reviewer=by;a.reviewerId=u.userId;a.reviewedVersion=a.version;if(p.role==='admin')event(w,by,'Administrator expert review',a.title);a.reviewedAt=new Date().toISOString();a.status=a.critical?'owner_review':'verified';a.kind=a.critical?'Proposed interpretation':'Approved rule';if(!a.critical)w.questions.filter((q:any)=>q.assetId===a.id).forEach((q:any)=>q.status='resolved');receipt(w,by,a.critical?`${a.title} verified by expert; business-owner sign-off still required.`:`${a.title} verified. One knowledge gap closed.`,[a.id]);message=a.critical?'Expert review complete. Owner sign-off required.':'Requirement verified.';break;}
 case 'owner_signoff':{permitted(p.role,['admin','owner']);const a=getAsset();if(a.status!=='owner_review'||!a.reviewer||a.reviewedVersion!==a.version)throw new AppError('Expert review must be completed first.');a.ownerApproval=by;a.ownerId=u.userId;if(p.role==='admin')event(w,by,'Administrator owner sign-off',a.title);a.status='verified';a.kind='Approved rule';w.questions.filter((q:any)=>q.assetId===a.id).forEach((q:any)=>q.status='resolved');receipt(w,by,`${a.title} received business-owner approval. The critical blocker is closed.`,[a.id]);message='Critical rule approved.';break;}
 case 'reject':{permitted(p.role,['admin','expert','owner']);const a=getAsset();const reason=text(b.reason,2000);if(!reason)throw new AppError('Record what needs clarification.');invalidate(w,[a.id]);a.status='draft';a.reviewer=undefined;a.ownerApproval=undefined;a.kind='Proposed interpretation';w.questions.unshift({id:crypto.randomUUID(),assetId:a.id,text:reason,why:'Expert requested clarification.',effort:'3 minutes',assignedTo:a.owner,status:'suggested',answer:'',createdBy:by});message='Returned for clarification. Follow-up needs question approval.';break;}
 case 'blueprint':{permitted(p.role,['admin','owner']);const scope=text(b.scope,500);if(!scope)throw new AppError('Describe the scope.');if(scope!==w.scope){w.scope=scope;w.blueprintVersion++;invalidate(w,w.assets.map((a:any)=>a.id));}w.client=text(b.client,120)||w.client;message='Scope version saved. Changed scope requires revalidation.';break;}
 case 'add_requirement':{permitted(p.role,['admin','owner']);const title=text(b.title,200);if(!title)throw new AppError('Name the requirement.');w.assets.push({id:crypto.randomUUID(),title,category:text(b.category,100)||'Process maps',critical:!!b.critical,owner:text(b.owner,200)||by,status:'missing',content:'',acceptance:text(b.acceptance,2000)||'Explanation, evidence, owner and expert approval.',evidence:[],version:1,conflict:'',kind:'Proposed interpretation',fields:['Explanation','Evidence','Owner','Acceptance criteria']});w.blueprintVersion++;message='Requirement added; coverage denominator updated.';break;}
 case 'exclude':{permitted(p.role,['admin','owner']);const a=getAsset(),reason=text(b.reason,1000);if(!reason)throw new AppError('Record a scoped exclusion reason.');invalidate(w,[a.id]);a.status='excluded';a.exclusion=reason;w.blueprintVersion++;w.questions.filter((q:any)=>q.assetId===a.id).forEach((q:any)=>q.status='resolved');message='Exclusion approved and retained in the blueprint history.';break;}
 case 'reopen':{permitted(p.role,['admin','expert','owner']);const a=getAsset();invalidate(w,[a.id]);if(a.status==='missing')a.status='draft';message='Requirement and dependent tests reopened.';break;}
 case 'expert':{permitted(p.role,['admin','expert','owner']);if(!text(b.name)||!text(b.role)||!text(b.proof))throw new AppError('Name, responsibility, and expertise evidence are required.');w.experts.push({name:text(b.name,120),role:text(b.role,120),coverage:text(b.coverage,400),proof:text(b.proof,1500)});message='Expertise and scope recorded.';break;}
 case 'settings':{w.settings={quietStart:/^\d\d:\d\d$/.test(b.quietStart)?b.quietStart:w.settings.quietStart,quietEnd:/^\d\d:\d\d$/.test(b.quietEnd)?b.quietEnd:w.settings.quietEnd,frequency:text(b.frequency,100)||w.settings.frequency,paused:!!b.paused,recognition:!!b.recognition};message='Workspace notification preferences saved.';break;}
 case 'approve_test':{permitted(p.role,['admin','expert']);const t=w.tests.find((t:any)=>t.id===b.testId);if(!t)throw new AppError('Test not found.');for(const run of w.runs)if(run.results.some((r:any)=>r.caseId===t.id))run.stale=true;t.version=(t.version||1)+1;t.input=text(b.input,3000)||t.input;t.expected=text(b.expected,3000)||t.expected;t.approved=true;message='Test case approved.';break;}
 case 'add_test':{permitted(p.role,['admin','expert','owner']);getAsset();if(!text(b.input)||!text(b.expected))throw new AppError('Add a test input and expected behavior.');w.tests.push({id:crypto.randomUUID(),name:text(b.name,150)||'New acceptance case',input:text(b.input,3000),expected:text(b.expected,3000),split:['fixed','held-out','regression'].includes(b.split)?b.split:'fixed',approved:false,assetIds:[b.assetId]});message='Acceptance case added for review.';break;}
 case 'grade':{permitted(p.role,['admin','expert']);const run=w.runs.find((r:any)=>r.id===b.runId),r=run?.results.find((r:any)=>r.caseId===b.caseId);if(!r||run?.stale)throw new AppError('Run not found or stale. Run the current context first.');r.beforePass=b.beforePass===true;r.afterPass=b.afterPass===true;r.gradedBy=by;message='Expert evaluation recorded.';break;}
 case 'test_failure':{permitted(p.role,['admin','expert','owner']);const t=w.tests.find((t:any)=>t.id===b.testId);if(!t)throw new AppError('Test not found.');if(b.kind==='context'){invalidate(w,t.assetIds);for(const id of t.assetIds)w.questions.unshift({id:crypto.randomUUID(),assetId:id,text:`What operating knowledge is missing for this failed case: ${t.input}`,why:'Evaluation exposed a context gap.',effort:'5 minutes',assignedTo:'Domain expert',status:'suggested',answer:'',createdBy:by});message='Context failure returned to discovery.';}else{event(w,by,'Engineering issue',text(b.reason,1500)||t.name);message='Engineering issue recorded in the audit trail.';}break;}
 case 'release':{permitted(p.role,['admin','owner']);const r=readiness(w);if(!r.ready)throw new AppError('Every applicable requirement must be verified before release.');const version=w.releases.length+1,at=new Date().toISOString();const assets=w.assets.filter((a:any)=>a.status==='verified');const sourceIds=new Set(assets.flatMap((a:any)=>a.evidence.map((e:any)=>e.sourceId)));const pack={format:'discovery-context/1',projectId:p.id,client:w.client,scope:w.scope,blueprintVersion:w.blueprintVersion,releaseVersion:version,effectiveAt:at,sample:w.sample,approvedBy:by,assets:structuredClone(assets),sources:w.sources.filter((s:any)=>sourceIds.has(s.id)).map(({key,...s}:any)=>s),exclusions:w.assets.filter((a:any)=>a.status==='excluded'),blockers:[],evaluations:structuredClone(w.runs),tests:structuredClone(w.tests),access:'Reviewers and owners only; preserve source restrictions downstream.',rapid:'Versioned export; live Rapid connection not configured.'};w.releases.unshift({id:crypto.randomUUID(),version,at,by,package:pack});message=`Context v${version} published. Immutable export is ready.`;break;}
 case 'refresh':{permitted(p.role,['admin','expert','owner']);const s=w.sources.find((s:any)=>s.id===b.sourceId);if(!s)throw new AppError('Select the changed source.');const ids=[...new Set([...s.assetIds,...w.assets.filter((a:any)=>a.evidence.some((e:any)=>e.sourceId===s.id)).map((a:any)=>a.id)])] as string[];invalidate(w,ids);message=`${ids.length} dependent requirements reopened for source revalidation.`;break;}
 case 'invite':{permitted(p.role,['admin']);const role:Role=['expert','owner','contributor','viewer'].includes(b.role)?b.role:'contributor';const token=crypto.randomUUID()+crypto.randomUUID();const tokenHash=await hash(token);effects=marker=>[db().prepare("INSERT INTO invites(hash,project_id,role,expires) SELECT ?,?,?,? WHERE EXISTS (SELECT 1 FROM projects WHERE id=? AND json_extract(state,'$.events[0].id')=?)").bind(tokenHash,p.id,role,new Date(Date.now()+7*86400000).toISOString(),p.id,marker)];extra.invitePath=`/?invite=${token}`;message='Single-use invitation created. Expires in seven days.';break;}
 case 'change_role':{permitted(p.role,['admin']);if(b.userId===u.userId)throw new AppError('Keep your administrator access.');const role=['expert','owner','contributor','viewer'].includes(b.role)?b.role:null;if(!role)throw new AppError('Choose a role.');effects=marker=>[db().prepare("UPDATE members SET role=? WHERE project_id=? AND user_id=? AND EXISTS (SELECT 1 FROM projects WHERE id=? AND json_extract(state,'$.events[0].id')=?)").bind(role,p.id,text(b.userId,200),p.id,marker)];message='Member role updated.';break;}
 default:throw new AppError('Unknown action.');
 }
 const revision=await save(p,by,action,message,effects);return Response.json({message,revision,...extra});
 }catch(e){return fail(e)}}
